export var mockUserData = {};
mockUserData.thgreasi = {
  "login": "thgreasi",
  "id": 1295829,
  "avatar_url": "https://avatars.githubusercontent.com/u/1295829?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/thgreasi",
  "html_url": "https://github.com/thgreasi",
  "followers_url": "https://api.github.com/users/thgreasi/followers",
  "following_url": "https://api.github.com/users/thgreasi/following{/other_user}",
  "gists_url": "https://api.github.com/users/thgreasi/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/thgreasi/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/thgreasi/subscriptions",
  "organizations_url": "https://api.github.com/users/thgreasi/orgs",
  "repos_url": "https://api.github.com/users/thgreasi/repos",
  "events_url": "https://api.github.com/users/thgreasi/events{/privacy}",
  "received_events_url": "https://api.github.com/users/thgreasi/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Thodoris Greasidis",
  "company": null,
  "blog": null,
  "location": "Greece",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 35,
  "public_gists": 10,
  "followers": 54,
  "following": 12,
  "created_at": "2011-12-30T23:33:05Z",
  "updated_at": "2016-07-25T18:40:46Z"
};
