// https://api.github.com/search/users?q=thgre
export var mockUserSearchData = {};
mockUserSearchData.thgre = {
  "total_count": 9,
  "incomplete_results": false,
  "items": [
    {
      "login": "thgreasi",
      "id": 1295829,
      "avatar_url": "https://avatars.githubusercontent.com/u/1295829?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgreasi",
      "html_url": "https://github.com/thgreasi",
      "followers_url": "https://api.github.com/users/thgreasi/followers",
      "following_url": "https://api.github.com/users/thgreasi/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgreasi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgreasi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgreasi/subscriptions",
      "organizations_url": "https://api.github.com/users/thgreasi/orgs",
      "repos_url": "https://api.github.com/users/thgreasi/repos",
      "events_url": "https://api.github.com/users/thgreasi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgreasi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 41.2174
    },
    {
      "login": "thgrendel",
      "id": 651852,
      "avatar_url": "https://avatars.githubusercontent.com/u/651852?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgrendel",
      "html_url": "https://github.com/thgrendel",
      "followers_url": "https://api.github.com/users/thgrendel/followers",
      "following_url": "https://api.github.com/users/thgrendel/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgrendel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgrendel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgrendel/subscriptions",
      "organizations_url": "https://api.github.com/users/thgrendel/orgs",
      "repos_url": "https://api.github.com/users/thgrendel/repos",
      "events_url": "https://api.github.com/users/thgrendel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgrendel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 10.017351
    },
    {
      "login": "thgregory93",
      "id": 18596646,
      "avatar_url": "https://avatars.githubusercontent.com/u/18596646?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgregory93",
      "html_url": "https://github.com/thgregory93",
      "followers_url": "https://api.github.com/users/thgregory93/followers",
      "following_url": "https://api.github.com/users/thgregory93/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgregory93/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgregory93/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgregory93/subscriptions",
      "organizations_url": "https://api.github.com/users/thgregory93/orgs",
      "repos_url": "https://api.github.com/users/thgregory93/repos",
      "events_url": "https://api.github.com/users/thgregory93/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgregory93/received_events",
      "type": "User",
      "site_admin": false,
      "score": 7.6995544
    },
    {
      "login": "thgreatga",
      "id": 22237196,
      "avatar_url": "https://avatars.githubusercontent.com/u/22237196?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgreatga",
      "html_url": "https://github.com/thgreatga",
      "followers_url": "https://api.github.com/users/thgreatga/followers",
      "following_url": "https://api.github.com/users/thgreatga/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgreatga/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgreatga/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgreatga/subscriptions",
      "organizations_url": "https://api.github.com/users/thgreatga/orgs",
      "repos_url": "https://api.github.com/users/thgreatga/repos",
      "events_url": "https://api.github.com/users/thgreatga/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgreatga/received_events",
      "type": "User",
      "site_admin": false,
      "score": 7.6995544
    },
    {
      "login": "thgreiner",
      "id": 8747023,
      "avatar_url": "https://avatars.githubusercontent.com/u/8747023?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgreiner",
      "html_url": "https://github.com/thgreiner",
      "followers_url": "https://api.github.com/users/thgreiner/followers",
      "following_url": "https://api.github.com/users/thgreiner/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgreiner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgreiner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgreiner/subscriptions",
      "organizations_url": "https://api.github.com/users/thgreiner/orgs",
      "repos_url": "https://api.github.com/users/thgreiner/repos",
      "events_url": "https://api.github.com/users/thgreiner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgreiner/received_events",
      "type": "User",
      "site_admin": false,
      "score": 6.8274326
    },
    {
      "login": "thgready",
      "id": 13277660,
      "avatar_url": "https://avatars.githubusercontent.com/u/13277660?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgready",
      "html_url": "https://github.com/thgready",
      "followers_url": "https://api.github.com/users/thgready/followers",
      "following_url": "https://api.github.com/users/thgready/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgready/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgready/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgready/subscriptions",
      "organizations_url": "https://api.github.com/users/thgready/orgs",
      "repos_url": "https://api.github.com/users/thgready/repos",
      "events_url": "https://api.github.com/users/thgready/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgready/received_events",
      "type": "User",
      "site_admin": false,
      "score": 6.8274326
    },
    {
      "login": "thgreen100",
      "id": 6625534,
      "avatar_url": "https://avatars.githubusercontent.com/u/6625534?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgreen100",
      "html_url": "https://github.com/thgreen100",
      "followers_url": "https://api.github.com/users/thgreen100/followers",
      "following_url": "https://api.github.com/users/thgreen100/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgreen100/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgreen100/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgreen100/subscriptions",
      "organizations_url": "https://api.github.com/users/thgreen100/orgs",
      "repos_url": "https://api.github.com/users/thgreen100/repos",
      "events_url": "https://api.github.com/users/thgreen100/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgreen100/received_events",
      "type": "User",
      "site_admin": false,
      "score": 6.8274326
    },
    {
      "login": "thgregoire",
      "id": 16803610,
      "avatar_url": "https://avatars.githubusercontent.com/u/16803610?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgregoire",
      "html_url": "https://github.com/thgregoire",
      "followers_url": "https://api.github.com/users/thgregoire/followers",
      "following_url": "https://api.github.com/users/thgregoire/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgregoire/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgregoire/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgregoire/subscriptions",
      "organizations_url": "https://api.github.com/users/thgregoire/orgs",
      "repos_url": "https://api.github.com/users/thgregoire/repos",
      "events_url": "https://api.github.com/users/thgregoire/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgregoire/received_events",
      "type": "User",
      "site_admin": false,
      "score": 6.8274326
    },
    {
      "login": "thgreatawais",
      "id": 22323521,
      "avatar_url": "https://avatars.githubusercontent.com/u/22323521?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thgreatawais",
      "html_url": "https://github.com/thgreatawais",
      "followers_url": "https://api.github.com/users/thgreatawais/followers",
      "following_url": "https://api.github.com/users/thgreatawais/following{/other_user}",
      "gists_url": "https://api.github.com/users/thgreatawais/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thgreatawais/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thgreatawais/subscriptions",
      "organizations_url": "https://api.github.com/users/thgreatawais/orgs",
      "repos_url": "https://api.github.com/users/thgreatawais/repos",
      "events_url": "https://api.github.com/users/thgreatawais/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thgreatawais/received_events",
      "type": "User",
      "site_admin": false,
      "score": 6.8274326
    }
  ]
};
